Ocd 3212 - unretire CDC's NHSN CDA Validator and retire HL7 CDA National Health Care Surveys Validator
chpladmin/chpl-data-model pull request #341
Opened 2019-12-09 16:39 UTC by tmy1313

OCD-3212

2019-12-09 18:05 UTC, andlar requested changes

2019-12-09 18:05 UTC, andlar commented on v-next.sql
> +\i ocd-3186.sql
This PR shouldn't be including 3186 changes as well

2019-12-09 19:24 UTC, andlar commented on dev/openchpl_views.sql
> +                  GROUP BY certification_status_event.certified_product_id
This shouldn't be here either

2019-12-11 16:23 UTC, andlar approved these changes

2019-12-11 17:12 UTC, kekey1 approved these changes

2019-12-11 19:21 UTC, merged