OCD-3147 - add questionable activity triggers for adding b3 criteria
chpladmin/chpl-data-model pull request #344
Opened 2019-12-12 16:05 UTC by tmy1313

OCD-3147

2019-12-12 16:10 UTC, kekey1 submitted a review, later dismissed

2019-12-12 16:27 UTC, andlar submitted a review, later dismissed

2019-12-18 15:26 UTC, andlar requested changes

2019-12-18 15:26 UTC, andlar commented on dev/openchpl_preload.sql
> +('ICS added when certification criteria 170.315(b)(3) is on a current listing', 'Listing', -1);
```suggestion
('ICS added when Certification Criteria 170.315(b)(3) is on a current listing', 'Listing', -1);
```

2019-12-18 15:26 UTC, andlar commented on ocd-3147.sql
> +SELECT 'ICS added when certification criteria 170.315(b)(3) is on a current listing', 'Listing', -1
```suggestion
SELECT 'ICS added when Certification Criteria 170.315(b)(3) is on a current listing', 'Listing', -1
```

2019-12-19 18:32 UTC, andlar approved these changes

2019-12-19 19:21 UTC, kekey1 approved these changes

2019-12-19 20:58 UTC, merged