Ocd 3393 - Add new data elements for Real World Testing
chpladmin/chpl-data-model pull request #373
Opened 2020-08-25 17:54 UTC by tmy1313

2020-08-26 14:23 UTC, andlar submitted a review, later dismissed

2020-08-26 16:48 UTC, kekey1 submitted a review, later dismissed

2020-08-26 16:48 UTC, kekey1 commented on dev/openchpl_views.sql
> +    cp.rwt_plan_url,
I don't think this view has the other/original rwt column rwt_eligibility_year. Does it need that one too (like the details view has)?

2020-08-27 13:05 UTC, kekey1 submitted a review, later dismissed

2020-08-30 22:19 UTC, andlar commented on ocd-3393.sql
> +ADD COLUMN IF NOT EXISTS rwt_plan_submission_date date NULL;
This column is a `date` type. The value in the API is a `long` type. I think the API is wrong, but if it's correct then this is wrong

2020-09-03 12:41 UTC, andlar approved these changes, later dismissed

2020-09-21 19:12 UTC, kekey1 submitted a review, later dismissed

2020-09-21 19:43 UTC, andlar approved these changes, later dismissed

2020-10-01 14:13 UTC, andlar approved these changes, later dismissed

2020-10-01 14:25 UTC, kekey1 submitted a review, later dismissed

2020-10-07 17:55 UTC, andlar requested changes

2020-10-07 17:55 UTC, andlar commented on ocd-3393.sql
> +DROP COLUMN IF EXISTS rwt_plan_url;
These change the tables as they're defined in the data-model, right? So shouldn't this PR have a change to the dev/data-model.sql file as well?

2020-10-08 12:19 UTC, andlar approved these changes

2020-10-12 14:09 UTC, kekey1 approved these changes

2020-10-13 15:15 UTC, merged