OCD-3644 - Allow criteria to have Service Base URL List value
chpladmin/chpl-data-model pull request #408
Opened 2021-04-23 11:45 UTC by andlar

2021-04-26 12:44 UTC, kekey1 requested changes

2021-04-26 12:44 UTC, kekey1 commented on dev/openchpl_data-model.sql
> +        service_base_url_list text;
should not have a semicolon at the end, i think?

2021-04-26 14:47 UTC, kekey1 approved these changes

2021-04-27 13:37 UTC, tmy1313 approved these changes

2021-05-06 18:03 UTC, merged