OCD-3586 - Update README documentation for each project
chpladmin/chpl-data-model pull request #411
Opened 2021-05-24 15:50 UTC by tmy1313

OCD-3586

2021-05-24 16:40 UTC, andlar requested changes

2021-05-24 16:40 UTC, andlar commented on README.md
> +These scripts are run each time the database is updated.  These scripts will drop all database objects associatedw ith the script and recreate the objects.
```suggestion
These scripts are run each time the database is updated. These scripts will drop all database objects associated with the script and recreate the objects.
```

2021-05-24 16:40 UTC, andlar commented on README.md
> +* Create new file or append canges to existing `changes/ocd-XXXX.sql` which corresponds to the ticket the change is associated to
```suggestion
* Create a new file or append changes to an existing `changes/ocd-XXXX.sql` file which corresponds to the ticket the change is associated to
```

2021-05-24 16:40 UTC, andlar commented on README.md
> +## Updating you local data to match another environment
```suggestion
## Updating your local data to match another environment
```

2021-05-24 16:40 UTC, andlar commented on README.md
> +Sometimes database changes may require scripting not defined here to perform the required changes.  Those situations should be handled on a case by case basis.
```suggestion
Sometimes database changes may require scripting not defined here to perform the required changes. Those situations should be handled on a case by case basis.
```

2021-05-24 16:40 UTC, andlar commented on README.md
> +Run the `load-pending-changes.sh` script.  This will execute:
```suggestion
Run the `load-pending-changes.sh` script. This will execute:
```

2021-05-25 14:58 UTC, kekey1 requested changes

2021-05-25 14:58 UTC, kekey1 commented on README.md
> +* Create new file or append canges to existing `changes/ocd-XXXX.sql` which corresponds to the ticket the change is associated to
```suggestion
* Create new file or append changes to existing `changes/ocd-XXXX.sql` which corresponds to the ticket the change is associated to
```

2021-05-25 14:58 UTC, kekey1 commented on README.md
>  Next, run the script `dev/reset.sh` or `dev/reset.bat` from the `/dev` directory. These two scripts remove any previous OpenCHPL data model installation, with the associated roles, then recreate the
Edit to refer to the program as "CHPL" vs "OpenCHPL"?

2021-05-26 13:38 UTC, kekey1 approved these changes

2021-05-26 13:46 UTC, andlar approved these changes

2021-05-26 16:25 UTC, palakpatel311 approved these changes

2021-06-01 14:00 UTC, merged