OCD-3621: Add/Edit Optional Standards
chpladmin/chpl-data-model pull request #413
Opened 2021-05-28 16:24 UTC by andlar

2021-05-28 23:52 UTC, kekey1 approved these changes, later dismissed

2021-06-02 14:08 UTC, kekey1 requested changes

2021-06-02 14:08 UTC, kekey1 commented on changes/ocd-3621.sql
> + CONSTRAINT optional_standard_criteria_map_fk FOREIGN KEY (criterion_id)
This constraint name I think should be criterion_id_fk

2021-06-02 14:08 UTC, kekey1 commented on dummy-data.sql
> +('HL7® IG for CDA® R2: IHE Health Story Consolidation, DSTU R1.1 ', -1),
trailing space in optional_standard column value

2021-06-02 14:59 UTC, kekey1 approved these changes, later dismissed

2021-06-02 20:29 UTC, tmy1313 submitted a review, later dismissed

2021-06-21 13:33 UTC, kekey1 approved these changes

2021-06-21 15:50 UTC, tmy1313 approved these changes

2021-06-21 16:26 UTC, merged