OCD-2973 - Revise list of test tools to select for a 2015 Edition listing
chpladmin/chpl-data-model pull request #432
Opened 2021-09-10 01:50 UTC by tmy1313

2021-09-13 12:59 UTC, andlar reviewed
I only see changes to the running database. Don't we need, at least, an addition to the criterion_attribute table in the dev/data-model.sql file? As well as the new mapping table?

2021-09-14 15:33 UTC, kekey1 requested changes

2021-09-14 15:33 UTC, kekey1 commented on changes/ocd-2973.sql
> +SELECT 'NCPDP Electronic Prescribing (eRx) Testing Tool', 1
Is the last_modified_user the value you intended? I was thinking we normally use -1.

2021-09-14 15:33 UTC, kekey1 commented on changes/ocd-2973.sql
> +SELECT 'NIST General Validation Tool (GVT)', 1
Same thing with 1 vs -1

2021-09-14 15:33 UTC, kekey1 commented on changes/ocd-2973.sql
> +	test_tool = EXCLUDED.test_tool;
Just curious - what is EXCLUDED?

2021-09-14 15:34 UTC, kekey1 requested changes
Agree with Andrew's comment about needing some changes in data-model.sql

2021-09-16 12:53 UTC, andlar commented on dev/openchpl_data-model.sql
> +CREATE TABLE openchpl.listing_cures_status_statistic_by_acb (
I don't think this table should be here

2021-09-16 15:22 UTC, andlar commented on changes/ocd-2973.sql
> +	'This endpoint is deprecated and will be removed in a future release. The test_tools are now dependent on the criteria they are associted with and can be found in the CertifiedProductSearchDetails.'
```suggestion
	'This endpoint is deprecated and will be removed in a future release. The test_tools are now dependent on the criteria they are associated with and can be found in the CertifiedProductSearchDetails.',
```

2021-09-17 11:42 UTC, andlar approved these changes, later dismissed

2021-09-17 14:45 UTC, kekey1 approved these changes, later dismissed

2021-09-30 16:11 UTC, andlar approved these changes

2021-09-30 16:45 UTC, kekey1 approved these changes

2021-09-30 18:46 UTC, merged