OCD-3693 - Automate Cures Reporting Phase 1 Charts (Charts 4-6)
chpladmin/chpl-data-model pull request #435
Opened 2021-09-30 16:57 UTC by tmy1313

2021-10-01 18:36 UTC, kekey1 requested changes

2021-10-01 18:36 UTC, kekey1 commented on dev/openchpl_data-model.sql
> +CREATE TABLE IF NOT EXISTS openchpl.cures_listing_statistics_by_acb (
"IF NOT EXISTS" may not be needed here

2021-10-01 18:36 UTC, kekey1 commented on changes/ocd-3693.sql
> +);
Do we want the audit functions with these tables? They feel temporary-ish (like for 3 years) so maybe we do not... but wanted to ask.

2021-10-04 13:34 UTC, andlar approved these changes, later dismissed

2021-10-04 14:28 UTC, andlar commented on dev/openchpl_data-model.sql
> +<<<<<<< HEAD
This doesn't look right

2021-10-06 13:59 UTC, andlar submitted a review, later dismissed

2021-10-06 14:07 UTC, kekey1 approved these changes, later dismissed

2021-10-26 13:57 UTC, andlar requested changes

2021-10-26 13:57 UTC, andlar commented on dev/openchpl_data-model.sql
> +>>>>>>> staging
This shouldn't be here, right?

2021-10-26 13:57 UTC, andlar commented on dev/openchpl_data-model.sql
> +<<<<<<< HEAD
Merge conflict issue?

2021-10-27 13:01 UTC, kekey1 approved these changes

2021-10-27 13:47 UTC, andlar approved these changes

2021-10-27 14:35 UTC, merged