OCD-3440: Remove authority/user_permission_id field, add deprecated fields to table data
chpladmin/chpl-data-model pull request #441
Opened 2021-10-28 14:17 UTC by kekey1

2021-10-28 16:03 UTC, andlar requested changes

2021-10-28 16:03 UTC, andlar commented on changes/ocd-3440.sql
> +SELECT 5, 'surveillance -> authority', '2022-04-15', 'This field is deprecated and will be removed from the response data in a future release.', -1
This feature likely won't get to PROD until the 15th of November, and if we give six months for deprecation warnings, then the removal_date ought to be in May

```suggestion
SELECT 5, 'surveillance -> authority', '2022-05-15', 'This field is deprecated and will be removed from the response data in a future release.', -1
```

2021-11-02 22:55 UTC, tmy1313 approved these changes

2021-11-03 11:17 UTC, andlar approved these changes

2021-11-12 15:13 UTC, merged