OCD-3717 - Add new Attestation submission process
chpladmin/chpl-data-model pull request #450
Opened 2022-01-27 14:36 UTC by tmy1313

2022-01-27 15:28 UTC, andlar requested changes
When creating new tables we need to update the audit-trigger file to include adding triggers to those tables

2022-01-27 16:30 UTC, kekey1 requested changes
I'm so sorry to add this comment if it opens a can of worms. I think we need changes to the soft_delete script as well for when a developer is deleted (happens during merge or split). I am not sure how attestations are/should be affected by developer merge and split.

2022-01-28 14:50 UTC, kekey1 submitted a review, later dismissed

2022-02-01 15:41 UTC, andlar approved these changes, later dismissed

2022-02-01 15:52 UTC, kekey1 approved these changes, later dismissed

2022-02-04 15:25 UTC, andlar approved these changes, later dismissed

2022-02-04 15:34 UTC, kekey1 approved these changes, later dismissed

2022-02-08 14:18 UTC, andlar approved these changes

2022-02-08 19:18 UTC, kekey1 approved these changes

2022-02-08 22:55 UTC, merged