OCD-3790 - Add controls to grant and limit access to Attestation submission process
chpladmin/chpl-data-model pull request #453
Opened 2022-02-23 18:10 UTC by tmy1313

2022-02-23 18:48 UTC, andlar requested changes

2022-02-23 18:48 UTC, andlar commented on changes/ocd-3790.sql
> +SELECT '2021-01-01', '2022-03-30', '2022-04-01', '2022-04-30', 'First Period', -1
```suggestion
SELECT '2020-07-01', '2022-03-31', '2022-04-01', '2022-04-30', 'First Period', -1
```

2022-02-25 13:04 UTC, andlar approved these changes, later dismissed

2022-02-25 18:56 UTC, kekey1 requested changes

2022-02-25 18:56 UTC, kekey1 commented on changes/ocd-3790.sql
> +	developer_id bigint NOT NULL,
Since this has a reference to developer_id, I was expecting to see something in the soft_delete triggers file.

2022-02-25 19:21 UTC, kekey1 approved these changes, later dismissed

2022-03-01 14:16 UTC, andlar approved these changes, later dismissed

2022-03-11 12:17 UTC, andlar approved these changes

2022-03-11 16:00 UTC, kekey1 approved these changes

2022-03-11 17:50 UTC, merged