OCD-3873 - Attestations from previous periods can be modified
chpladmin/chpl-data-model pull request #474
Opened 2022-06-21 17:28 UTC by tmy1313

OCD-3873

2022-06-22 18:02 UTC, kekey1 approved these changes

2022-06-22 18:04 UTC, kekey1 approved these changes

2022-06-22 23:36 UTC, kekey1 requested changes

2022-06-22 23:36 UTC, kekey1 commented on changes/ocd-3873.sql
> +INSERT INTO openchpl.deprecated_api (http_method, api_operation, change_description, removal_date, last_modified_user)
I think this is missing a new deprecated endpoint - for exceptions?

2022-06-24 13:51 UTC, kekey1 approved these changes

2022-06-27 11:50 UTC, andlar approved these changes

2022-07-19 20:07 UTC, merged