OCD-4446 - Add "up-to-date on code sets" to criteria on listings
chpladmin/chpl-data-model pull request #567
Opened 2024-01-23 15:59 UTC by tmy1313

2024-01-23 16:30 UTC, kekey1 approved these changes

2024-01-23 16:30 UTC, kekey1 commented on changes/ocd-4446.sql
> +update openchpl.certification_result
Worth putting in a clause here to not update "deleted = true" records?

2024-01-23 16:30 UTC, kekey1 commented on changes/ocd-4446.sql
> +update openchpl.certification_result
same question about deleted certification_result records

2024-01-23 16:35 UTC, kekey1 requested changes
Based on the ticket description I was expecting a new questionable activity trigger also

2024-01-25 14:54 UTC, kekey1 approved these changes

2024-01-25 16:28 UTC, andlar approved these changes

2024-02-21 14:07 UTC, closed without merging