feat: add tables to support Criteria Migration Report definition and …
chpladmin/chpl-data-model pull request #597
Opened 2024-06-17 19:35 UTC by tmy1313

…data

OCD-4597

2024-06-17 20:08 UTC, kekey1 submitted a review, later dismissed

2024-06-18 10:37 UTC, andlar requested changes

2024-06-18 10:37 UTC, andlar commented on changes/ocd-4597.sql
> +select 'HTI-1', '2024-03-12', 1
```suggestion
select 'HTI-1', '2024-03-11', 1
```

According to our team calendar, the effective date of HTI-1 was the eleventh

2024-06-18 17:12 UTC, andlar approved these changes

2024-06-18 17:44 UTC, kekey1 approved these changes

2024-06-25 17:18 UTC, merged