OCD-46866 - Power BI - Service Base URL List report
chpladmin/chpl-data-model pull request #616
Opened 2024-11-20 17:54 UTC by tmy1313

OCD-4686

2024-11-21 14:19 UTC, andlar submitted a review, later dismissed

2024-11-26 15:11 UTC, kekey1 requested changes

2024-11-26 15:11 UTC, kekey1 commented on changes/ocd-4686.sql
> +        'Service Base URL Listing Report',
Is this name right? I thought the term was "Service Base URL List" but this says "Listing". Is it something different?

2024-11-26 16:00 UTC, kekey1 approved these changes

2024-12-05 14:17 UTC, andlar approved these changes

2024-12-11 15:35 UTC, merged